site_name: Remi's Documents
site_url: https://example.com/
repo_url: https://github.com/remi-reyes/Documentations

extra_css:
  - stylesheets/extra.css

theme:
    language: en
    name: material
    palette:
        scheme: light
    features:
      - navigation.instant
      - navigation.tabs

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - codehilite:
        use_pygments: true