site_name: Remi's Documents
site_url: https://remi-reyes.github.io/Documentations

repo_name: remi-reyes/Documentations
repo_url: https://github.com/remi-reyes/Documentations
edit_uri: ""

extra_css:
  - stylesheets/extra.css

theme:
    language: en
    name: material
    palette:
      - scheme: light
        toggle:
            icon: material/lightbulb-outline
            name: Switch to dark mode.
      - scheme: dark
        toggle:
            icon: material/lightbulb
            name: Switch to light mode.
    features:
      - navigation.instant
      - navigation.tabs

markdown_extensions:
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - codehilite:
        use_pygments: true